/* ============================================================================
   SCRIPT DDL COMPLETO - BANCO DE DADOS FIREBIRD 5.0
   SISTEMA DE GESTÃO INDUSTRIAL, PORTARIA, PRODUÇÃO E LOGÍSTICA
   Compatível com Firebird 5.0 - Suporte a Stored Procedures PSQL, Sequences e Triggers
   ============================================================================ */

-- Configuração inicial do Banco:
-- CREATE DATABASE 'localhost:/var/lib/firebird/data/SISTEMA_LOGISTICA.FDB'
--   USER 'SYSDBA' PASSWORD 'masterkey'
--   PAGE_SIZE 16384
--   DEFAULT CHARACTER SET UTF8;

-- Conectar ao banco antes de executar:
-- CONNECT 'localhost:/var/lib/firebird/data/SISTEMA_LOGISTICA.FDB' USER 'SYSDBA' PASSWORD 'masterkey';

SET SQL DIALECT 3;

/* ============================================================================
   1. SEQUENCES (GENERATORS)
   ============================================================================ */
CREATE SEQUENCE GEN_USUARIOS;
CREATE SEQUENCE GEN_VEICULOS;
CREATE SEQUENCE GEN_MOTORISTAS;
CREATE SEQUENCE GEN_CLIENTES;
CREATE SEQUENCE GEN_MOVIMENTOS;
CREATE SEQUENCE GEN_PRODUCAO_CONTROLE;
CREATE SEQUENCE GEN_AVARIAS_ITENS;
CREATE SEQUENCE GEN_ABASTECIMENTOS;
CREATE SEQUENCE GEN_ESTOQUE_PRODUTOS;
CREATE SEQUENCE GEN_ESTOQUE_AJUSTES;
CREATE SEQUENCE GEN_AUDITORIA_LOGS;

/* ============================================================================
   2. TABELAS PRINCIPAIS
   ============================================================================ */

-- 2.1 TABELA DE USUÁRIOS DO SISTEMA
CREATE TABLE TB_USUARIOS (
    ID BIGINT NOT NULL,
    UUID VARCHAR(64) NOT NULL,
    NOME VARCHAR(120) NOT NULL,
    USUARIO VARCHAR(60) NOT NULL,
    SENHA VARCHAR(255) NOT NULL,
    PERFIL VARCHAR(30) DEFAULT 'operador' NOT NULL, -- admin, operador, visualizador, motorista, supervisor
    UNIDADE VARCHAR(20) DEFAULT 'matriz' NOT NULL,  -- matriz, filial
    ATIVO CHAR(1) DEFAULT 'S' NOT NULL,
    CRIADO_EM TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT PK_TB_USUARIOS PRIMARY KEY (ID),
    CONSTRAINT UK_TB_USUARIOS_UUID UNIQUE (UUID),
    CONSTRAINT UK_TB_USUARIOS_LOGIN UNIQUE (USUARIO)
);

-- 2.2 TABELA DE MOTORISTAS
CREATE TABLE TB_MOTORISTAS (
    ID BIGINT NOT NULL,
    UUID VARCHAR(64) NOT NULL,
    NOME VARCHAR(120) NOT NULL,
    TIPO_MOTORISTA VARCHAR(20) DEFAULT 'interno' NOT NULL, -- interno, cliente, terceiro
    UNIDADE VARCHAR(20) DEFAULT 'matriz' NOT NULL,
    PERC_COMISSAO NUMERIC(5, 2) DEFAULT 0.00,
    TOLERANCIA_AVARIAS INTEGER DEFAULT 0,
    ATIVO CHAR(1) DEFAULT 'S' NOT NULL,
    CRIADO_EM TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT PK_TB_MOTORISTAS PRIMARY KEY (ID),
    CONSTRAINT UK_TB_MOTORISTAS_UUID UNIQUE (UUID)
);

-- 2.3 TABELA DE VEÍCULOS
CREATE TABLE TB_VEICULOS (
    ID BIGINT NOT NULL,
    UUID VARCHAR(64) NOT NULL,
    PLACA VARCHAR(12) NOT NULL,
    TIPO_VEICULO VARCHAR(40) NOT NULL,
    TIPO_PROPRIETARIO VARCHAR(20) DEFAULT 'proprio' NOT NULL, -- proprio, terceiro
    MODELO VARCHAR(80),
    MOTORISTA_PADRAO_ID BIGINT,
    CAPACIDADE_MEDIA INTEGER DEFAULT 0,
    UNIDADE VARCHAR(20) DEFAULT 'matriz' NOT NULL,
    IGNORA_FILA CHAR(1) DEFAULT 'N' NOT NULL,
    ATIVO CHAR(1) DEFAULT 'S' NOT NULL,
    CRIADO_EM TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT PK_TB_VEICULOS PRIMARY KEY (ID),
    CONSTRAINT UK_TB_VEICULOS_UUID UNIQUE (UUID),
    CONSTRAINT UK_TB_VEICULOS_PLACA UNIQUE (PLACA),
    CONSTRAINT FK_VEIC_MOTORISTA FOREIGN KEY (MOTORISTA_PADRAO_ID) REFERENCES TB_MOTORISTAS(ID) ON DELETE SET NULL
);

-- 2.4 TABELA DE CLIENTES
CREATE TABLE TB_CLIENTES (
    ID BIGINT NOT NULL,
    UUID VARCHAR(64) NOT NULL,
    CODIGO VARCHAR(40),
    NOME VARCHAR(150) NOT NULL,
    NOME_FANTASIA VARCHAR(150),
    TIPO_PESSOA VARCHAR(15) DEFAULT 'juridica', -- fisica, juridica
    CNPJ_CPF VARCHAR(25),
    RG_IE VARCHAR(25),
    ENDERECO VARCHAR(200),
    NUMERO VARCHAR(20),
    BAIRRO VARCHAR(80),
    CIDADE VARCHAR(80),
    UF CHAR(2),
    TELEFONE VARCHAR(30),
    UNIDADE VARCHAR(20) DEFAULT 'matriz' NOT NULL,
    COMPRA_NA_EMPRESA CHAR(1) DEFAULT 'N' NOT NULL,
    ATIVO CHAR(1) DEFAULT 'S' NOT NULL,
    CRIADO_EM TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT PK_TB_CLIENTES PRIMARY KEY (ID),
    CONSTRAINT UK_TB_CLIENTES_UUID UNIQUE (UUID)
);

-- 2.5 TABELA DE MOVIMENTOS DA PORTARIA E FLUXO
CREATE TABLE TB_MOVIMENTOS (
    ID BIGINT NOT NULL,
    UUID VARCHAR(64) NOT NULL,
    CODIGO_PRODUCAO VARCHAR(30), -- Ex: P-00123
    PLACA VARCHAR(12) NOT NULL,
    MOTORISTA VARCHAR(120) NOT NULL,
    MOTORISTA_ID BIGINT,
    VEICULO_ID BIGINT,
    CLIENTE_ID BIGINT,
    CLIENTE_NOME VARCHAR(150),
    TIPO_PROPRIETARIO VARCHAR(20) DEFAULT 'proprio' NOT NULL,
    TIPO_VEICULO VARCHAR(40) NOT NULL,
    ODOMETRO BIGINT DEFAULT 0,
    TIPO_FLUXO VARCHAR(15) DEFAULT 'entrada' NOT NULL, -- entrada, saida
    STATUS_MOVIMENTO VARCHAR(30) DEFAULT 'na_fila' NOT NULL, -- na_fila, em_atendimento, concluido, saida
    FINALIDADE VARCHAR(60),
    IGNORA_PRODUCAO CHAR(1) DEFAULT 'N' NOT NULL,
    UNIDADE VARCHAR(20) DEFAULT 'matriz' NOT NULL,
    DATA_ENTRADA TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    DATA_SAIDA TIMESTAMP,
    OPERADOR_ENTRADA VARCHAR(80),
    OPERADOR_SAIDA VARCHAR(80),
    AVALIADOR_CHECKLIST VARCHAR(80),
    CHECKLIST_OK CHAR(1) DEFAULT 'S' NOT NULL,
    CHECKLIST_DETALHES BLOB SUB_TYPE TEXT,
    ETAPA_KANBAN VARCHAR(40) DEFAULT 'aguardando_descarregamento',
    PAUSADO CHAR(1) DEFAULT 'N' NOT NULL,
    MOTIVO_PAUSA VARCHAR(120),
    TOTAL_PAUSA_MS BIGINT DEFAULT 0,
    CRIADO_EM TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    ATUALIZADO_EM TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT PK_TB_MOVIMENTOS PRIMARY KEY (ID),
    CONSTRAINT UK_TB_MOVIMENTOS_UUID UNIQUE (UUID),
    CONSTRAINT FK_MOV_MOTORISTA FOREIGN KEY (MOTORISTA_ID) REFERENCES TB_MOTORISTAS(ID) ON DELETE SET NULL,
    CONSTRAINT FK_MOV_VEICULO FOREIGN KEY (VEICULO_ID) REFERENCES TB_VEICULOS(ID) ON DELETE SET NULL,
    CONSTRAINT FK_MOV_CLIENTE FOREIGN KEY (CLIENTE_ID) REFERENCES TB_CLIENTES(ID) ON DELETE SET NULL
);

-- 2.6 TABELA DE CONTROLE DE PRODUÇÃO / INSPEÇÃO POR MOVIMENTO
CREATE TABLE TB_PRODUCAO_CONTROLE (
    ID BIGINT NOT NULL,
    UUID VARCHAR(64) NOT NULL,
    MOVIMENTO_ID BIGINT NOT NULL,
    OPERADOR VARCHAR(80),
    DESCARREGADO_TOTAL INTEGER DEFAULT 0 NOT NULL,
    CARREGADO_TOTAL INTEGER DEFAULT 0 NOT NULL,
    CORPO_ESTRANHO_TOTAL INTEGER DEFAULT 0 NOT NULL,
    MAL_LAVADO_TOTAL INTEGER DEFAULT 0 NOT NULL,
    VASILHAMES_RETORNADOS_LAVAR INTEGER DEFAULT 0 NOT NULL, -- soma de corpo estranho + mal lavado
    TAMPAS_UTILIZADAS INTEGER DEFAULT 0 NOT NULL,
    LACRES_UTILIZADOS INTEGER DEFAULT 0 NOT NULL,
    RETIRADA_VASILHAME_CARGA INTEGER DEFAULT 0 NOT NULL,
    PRODUCAO_CONCLUIDA CHAR(1) DEFAULT 'N' NOT NULL,
    DATA_INICIO TIMESTAMP,
    DATA_FIM TIMESTAMP,
    OBSERVACOES BLOB SUB_TYPE TEXT,
    CRIADO_EM TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    ATUALIZADO_EM TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT PK_TB_PRODUCAO_CONTROLE PRIMARY KEY (ID),
    CONSTRAINT UK_TB_PROD_UUID UNIQUE (UUID),
    CONSTRAINT UK_TB_PROD_MOVIMENTO UNIQUE (MOVIMENTO_ID),
    CONSTRAINT FK_PROD_MOVIMENTO FOREIGN KEY (MOVIMENTO_ID) REFERENCES TB_MOVIMENTOS(ID) ON DELETE CASCADE
);

-- 2.7 TABELA DE AVARIAS E OCORRÊNCIAS DETALHADAS (ITENS)
CREATE TABLE TB_AVARIAS_ITENS (
    ID BIGINT NOT NULL,
    UUID VARCHAR(64) NOT NULL,
    PRODUCAO_CONTROLE_ID BIGINT NOT NULL,
    FASE VARCHAR(20) NOT NULL,            -- 'descarregamento' OU 'carregamento'
    TIPO_AVARIA VARCHAR(80) NOT NULL,      -- 'vencido', 'microfuro', 'corpo estranho', 'mal lavado', 'quebra na maquina', etc.
    QUANTIDADE INTEGER DEFAULT 0 NOT NULL,
    CATEGORIA VARCHAR(30) DEFAULT 'avaria' NOT NULL, -- 'avaria', 'compra', 'retorno_lavagem', 'troca'
    DESCONTAR_MOTORISTA CHAR(1) DEFAULT 'S' NOT NULL,
    ORIGEM VARCHAR(30) DEFAULT 'frota_propria',
    CRIADO_EM TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT PK_TB_AVARIAS_ITENS PRIMARY KEY (ID),
    CONSTRAINT UK_TB_AVARIAS_UUID UNIQUE (UUID),
    CONSTRAINT FK_AVARIA_PRODUCAO FOREIGN KEY (PRODUCAO_CONTROLE_ID) REFERENCES TB_PRODUCAO_CONTROLE(ID) ON DELETE CASCADE
);

-- 2.8 TABELA DE ABASTECIMENTOS E POSTO
CREATE TABLE TB_ABASTECIMENTOS (
    ID BIGINT NOT NULL,
    UUID VARCHAR(64) NOT NULL,
    MOVIMENTO_ID BIGINT,
    PLACA VARCHAR(12) NOT NULL,
    MOTORISTA VARCHAR(120) NOT NULL,
    COMBUSTIVEL VARCHAR(30) NOT NULL, -- Diesel S10, Diesel S500, Arla 32, Gasolina
    LITROS NUMERIC(12, 3) NOT NULL,
    VALOR_TOTAL NUMERIC(12, 2) DEFAULT 0.00,
    ODOMETRO BIGINT,
    OPERADOR VARCHAR(80) NOT NULL,
    UNIDADE VARCHAR(20) DEFAULT 'matriz' NOT NULL,
    DATA_HORA TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT PK_TB_ABASTECIMENTOS PRIMARY KEY (ID),
    CONSTRAINT UK_TB_ABAST_UUID UNIQUE (UUID),
    CONSTRAINT FK_ABAST_MOVIMENTO FOREIGN KEY (MOVIMENTO_ID) REFERENCES TB_MOVIMENTOS(ID) ON DELETE SET NULL
);

-- 2.9 TABELA DE AUDITORIA E LOGS DO SISTEMA
CREATE TABLE TB_AUDITORIA_LOGS (
    ID BIGINT NOT NULL,
    TABELA_AFETADA VARCHAR(50) NOT NULL,
    REGISTRO_ID BIGINT,
    ACAO VARCHAR(20) NOT NULL, -- INSERT, UPDATE, DELETE, CANCELAR
    USUARIO VARCHAR(80) NOT NULL,
    DETALHES BLOB SUB_TYPE TEXT,
    DATA_HORA TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT PK_TB_AUDITORIA_LOGS PRIMARY KEY (ID)
);

/* ============================================================================
   3. ÍNDICES DE PERFORMANCE PARA MINERAÇÃO DE DADOS (BI) E PESQUISAS RÁPIDAS
   ============================================================================ */
CREATE INDEX IDX_MOV_DATA_ENTRADA ON TB_MOVIMENTOS(DATA_ENTRADA);
CREATE INDEX IDX_MOV_PLACA ON TB_MOVIMENTOS(PLACA);
CREATE INDEX IDX_MOV_STATUS ON TB_MOVIMENTOS(STATUS_MOVIMENTO);
CREATE INDEX IDX_MOV_UNIDADE ON TB_MOVIMENTOS(UNIDADE);
CREATE INDEX IDX_AVAR_TIPO ON TB_AVARIAS_ITENS(TIPO_AVARIA);
CREATE INDEX IDX_AVAR_CATEGORIA ON TB_AVARIAS_ITENS(CATEGORIA);
CREATE INDEX IDX_ABAST_DATA ON TB_ABASTECIMENTOS(DATA_HORA);
CREATE INDEX IDX_ABAST_PLACA ON TB_ABASTECIMENTOS(PLACA);

/* ============================================================================
   4. TRIGGERS AUTOMÁTICOS PARA AUTO-INCREMENTO (SEQUENCES)
   ============================================================================ */
SET TERM ^ ;

CREATE OR ALTER TRIGGER TRG_BI_TB_USUARIOS FOR TB_USUARIOS
ACTIVE BEFORE INSERT POSITION 0
AS
BEGIN
  IF (NEW.ID IS NULL) THEN
    NEW.ID = NEXT VALUE FOR GEN_USUARIOS;
END^

CREATE OR ALTER TRIGGER TRG_BI_TB_VEICULOS FOR TB_VEICULOS
ACTIVE BEFORE INSERT POSITION 0
AS
BEGIN
  IF (NEW.ID IS NULL) THEN
    NEW.ID = NEXT VALUE FOR GEN_VEICULOS;
END^

CREATE OR ALTER TRIGGER TRG_BI_TB_MOTORISTAS FOR TB_MOTORISTAS
ACTIVE BEFORE INSERT POSITION 0
AS
BEGIN
  IF (NEW.ID IS NULL) THEN
    NEW.ID = NEXT VALUE FOR GEN_MOTORISTAS;
END^

CREATE OR ALTER TRIGGER TRG_BI_TB_CLIENTES FOR TB_CLIENTES
ACTIVE BEFORE INSERT POSITION 0
AS
BEGIN
  IF (NEW.ID IS NULL) THEN
    NEW.ID = NEXT VALUE FOR GEN_CLIENTES;
END^

CREATE OR ALTER TRIGGER TRG_BI_TB_MOVIMENTOS FOR TB_MOVIMENTOS
ACTIVE BEFORE INSERT POSITION 0
AS
BEGIN
  IF (NEW.ID IS NULL) THEN
    NEW.ID = NEXT VALUE FOR GEN_MOVIMENTOS;
  NEW.ATUALIZADO_EM = CURRENT_TIMESTAMP;
END^

CREATE OR ALTER TRIGGER TRG_BU_TB_MOVIMENTOS FOR TB_MOVIMENTOS
ACTIVE BEFORE UPDATE POSITION 0
AS
BEGIN
  NEW.ATUALIZADO_EM = CURRENT_TIMESTAMP;
END^

CREATE OR ALTER TRIGGER TRG_BI_TB_PRODUCAO_CONTROLE FOR TB_PRODUCAO_CONTROLE
ACTIVE BEFORE INSERT POSITION 0
AS
BEGIN
  IF (NEW.ID IS NULL) THEN
    NEW.ID = NEXT VALUE FOR GEN_PRODUCAO_CONTROLE;
  NEW.ATUALIZADO_EM = CURRENT_TIMESTAMP;
END^

CREATE OR ALTER TRIGGER TRG_BU_TB_PRODUCAO_CONTROLE FOR TB_PRODUCAO_CONTROLE
ACTIVE BEFORE UPDATE POSITION 0
AS
BEGIN
  NEW.ATUALIZADO_EM = CURRENT_TIMESTAMP;
END^

CREATE OR ALTER TRIGGER TRG_BI_TB_AVARIAS_ITENS FOR TB_AVARIAS_ITENS
ACTIVE BEFORE INSERT POSITION 0
AS
BEGIN
  IF (NEW.ID IS NULL) THEN
    NEW.ID = NEXT VALUE FOR GEN_AVARIAS_ITENS;
END^

CREATE OR ALTER TRIGGER TRG_BI_TB_ABASTECIMENTOS FOR TB_ABASTECIMENTOS
ACTIVE BEFORE INSERT POSITION 0
AS
BEGIN
  IF (NEW.ID IS NULL) THEN
    NEW.ID = NEXT VALUE FOR GEN_ABASTECIMENTOS;
END^

/* ============================================================================
   5. STORED PROCEDURES DO FIREBIRD 5.0 (PSQL)
   ============================================================================ */

-- 5.1 PROCEDURE: REGISTRO DE ENTRADA NA PORTARIA
CREATE OR ALTER PROCEDURE SP_REGISTRAR_ENTRADA_PORTARIA (
    P_UUID VARCHAR(64),
    P_PLACA VARCHAR(12),
    P_MOTORISTA VARCHAR(120),
    P_TIPO_PROPRIETARIO VARCHAR(20),
    P_TIPO_VEICULO VARCHAR(40),
    P_ODOMETRO BIGINT,
    P_FINALIDADE VARCHAR(60),
    P_IGNORA_PRODUCAO CHAR(1),
    P_UNIDADE VARCHAR(20),
    P_OPERADOR VARCHAR(80),
    P_CHECKLIST_OK CHAR(1),
    P_CHECKLIST_DETALHES BLOB SUB_TYPE TEXT
)
RETURNS (
    O_MOVIMENTO_ID BIGINT,
    O_STATUS VARCHAR(30),
    O_CODIGO_PRODUCAO VARCHAR(30)
)
AS
  DECLARE VARIABLE V_SEQ_HOJE INTEGER;
  DECLARE VARIABLE V_ANO CHAR(4);
BEGIN
  V_ANO = EXTRACT(YEAR FROM CURRENT_DATE);
  
  -- Gerar código de produção sequencial diário/anual
  SELECT COALESCE(COUNT(*), 0) + 1
  FROM TB_MOVIMENTOS
  WHERE EXTRACT(YEAR FROM DATA_ENTRADA) = :V_ANO
  INTO :V_SEQ_HOJE;

  O_CODIGO_PRODUCAO = 'P-' || :V_ANO || '-' || LPAD(:V_SEQ_HOJE, 5, '0');
  
  IF (P_IGNORA_PRODUCAO = 'S') THEN
    O_STATUS = 'em_atendimento';
  ELSE
    O_STATUS = 'na_fila';

  INSERT INTO TB_MOVIMENTOS (
    UUID, CODIGO_PRODUCAO, PLACA, MOTORISTA, TIPO_PROPRIETARIO, TIPO_VEICULO,
    ODOMETRO, TIPO_FLUXO, STATUS_MOVIMENTO, FINALIDADE, IGNORA_PRODUCAO,
    UNIDADE, DATA_ENTRADA, OPERADOR_ENTRADA, CHECKLIST_OK, CHECKLIST_DETALHES,
    ETAPA_KANBAN
  ) VALUES (
    :P_UUID, :O_CODIGO_PRODUCAO, UPPER(:P_PLACA), :P_MOTORISTA, :P_TIPO_PROPRIETARIO, :P_TIPO_VEICULO,
    :P_ODOMETRO, 'entrada', :O_STATUS, :P_FINALIDADE, :P_IGNORA_PRODUCAO,
    :P_UNIDADE, CURRENT_TIMESTAMP, :P_OPERADOR, :P_CHECKLIST_OK, :P_CHECKLIST_DETALHES,
    'aguardando_descarregamento'
  ) RETURNING ID INTO :O_MOVIMENTO_ID;

  SUSPEND;
END^

-- 5.2 PROCEDURE: GRAVAR/ATUALIZAR CONTROLE DE PRODUÇÃO E VISTORIA
-- REGRA INDUSTRIAL CRUCIAL:
-- Itens marcados como 'retorno_lavagem' (ex: 'corpo estranho' e 'mal lavado')
-- alimentam o campo VASILHAMES_RETORNADOS_LAVAR e NÃO abatem o saldo de carga!
CREATE OR ALTER PROCEDURE SP_SALVAR_CONTROLE_PRODUCAO (
    P_MOVIMENTO_ID BIGINT,
    P_OPERADOR VARCHAR(80),
    P_DESCARREGADO INTEGER,
    P_TAMPAS INTEGER,
    P_LACRES INTEGER,
    P_RETIRADA_VASILHAME INTEGER,
    P_OBSERVACOES BLOB SUB_TYPE TEXT
)
RETURNS (
    O_PRODUCAO_ID BIGINT,
    O_TOTAL_LAVAR INTEGER,
    O_TOTAL_AVARIAS_REAIS INTEGER,
    O_TOTAL_CARGA_CALCULADA INTEGER
)
AS
  DECLARE VARIABLE V_EXISTS BIGINT;
  DECLARE VARIABLE V_CORPO_ESTRANHO INTEGER;
  DECLARE VARIABLE V_MAL_LAVADO INTEGER;
  DECLARE VARIABLE V_AVARIAS_DESCARGA INTEGER;
  DECLARE VARIABLE V_AVARIAS_CARGA INTEGER;
  DECLARE VARIABLE V_COMPRAS_ADICOES INTEGER;
BEGIN
  -- Verificar se já existe registro de produção para este movimento
  SELECT ID FROM TB_PRODUCAO_CONTROLE WHERE MOVIMENTO_ID = :P_MOVIMENTO_ID INTO :V_EXISTS;

  IF (V_EXISTS IS NULL) THEN
  BEGIN
    INSERT INTO TB_PRODUCAO_CONTROLE (
      UUID, MOVIMENTO_ID, OPERADOR, DESCARREGADO_TOTAL,
      TAMPAS_UTILIZADAS, LACRES_UTILIZADOS, RETIRADA_VASILHAME_CARGA,
      OBSERVACOES, DATA_INICIO
    ) VALUES (
      'PC-' || :P_MOVIMENTO_ID, :P_MOVIMENTO_ID, :P_OPERADOR, :P_DESCARREGADO,
      :P_TAMPAS, :P_LACRES, :P_RETIRADA_VASILHAME,
      :P_OBSERVACOES, CURRENT_TIMESTAMP
    ) RETURNING ID INTO :O_PRODUCAO_ID;
  END
  ELSE
  BEGIN
    UPDATE TB_PRODUCAO_CONTROLE
    SET OPERADOR = :P_OPERADOR,
        DESCARREGADO_TOTAL = :P_DESCARREGADO,
        TAMPAS_UTILIZADAS = :P_TAMPAS,
        LACRES_UTILIZADOS = :P_LACRES,
        RETIRADA_VASILHAME_CARGA = :P_RETIRADA_VASILHAME,
        OBSERVACOES = :P_OBSERVACOES
    WHERE ID = :V_EXISTS;

    O_PRODUCAO_ID = :V_EXISTS;
  END

  -- Calcular totalizadores de retorno de lavagem
  SELECT COALESCE(SUM(QUANTIDADE), 0)
  FROM TB_AVARIAS_ITENS
  WHERE PRODUCAO_CONTROLE_ID = :O_PRODUCAO_ID
    AND LOWER(TIPO_AVARIA) = 'corpo estranho'
  INTO :V_CORPO_ESTRANHO;

  SELECT COALESCE(SUM(QUANTIDADE), 0)
  FROM TB_AVARIAS_ITENS
  WHERE PRODUCAO_CONTROLE_ID = :O_PRODUCAO_ID
    AND LOWER(TIPO_AVARIA) = 'mal lavado'
  INTO :V_MAL_LAVADO;

  -- Total retornado para lavar = Corpo Estranho + Mal Lavado (ou outros da categoria retorno_lavagem)
  SELECT COALESCE(SUM(QUANTIDADE), 0)
  FROM TB_AVARIAS_ITENS
  WHERE PRODUCAO_CONTROLE_ID = :O_PRODUCAO_ID
    AND CATEGORIA = 'retorno_lavagem'
  INTO :O_TOTAL_LAVAR;

  -- Avarias Reais (exclui retorno de lavagem e compras/adições)
  SELECT COALESCE(SUM(QUANTIDADE), 0)
  FROM TB_AVARIAS_ITENS
  WHERE PRODUCAO_CONTROLE_ID = :O_PRODUCAO_ID
    AND CATEGORIA = 'avaria'
  INTO :O_TOTAL_AVARIAS_REAIS;

  -- Compras e Adições de Vasilhame de rota
  SELECT COALESCE(SUM(QUANTIDADE), 0)
  FROM TB_AVARIAS_ITENS
  WHERE PRODUCAO_CONTROLE_ID = :O_PRODUCAO_ID
    AND CATEGORIA = 'compra'
  INTO :V_COMPRAS_ADICOES;

  -- Carga calculada = Descarregado - Retirada - Avarias Reais + Adições
  -- Note: O_TOTAL_LAVAR NÃO abate a carga do veículo!
  O_TOTAL_CARGA_CALCULADA = :P_DESCARREGADO - :P_RETIRADA_VASILHAME - :O_TOTAL_AVARIAS_REAIS + :V_COMPRAS_ADICOES;
  IF (O_TOTAL_CARGA_CALCULADA < 0) THEN O_TOTAL_CARGA_CALCULADA = 0;

  -- Atualizar a tabela de controle com os totais calculados
  UPDATE TB_PRODUCAO_CONTROLE
  SET CORPO_ESTRANHO_TOTAL = :V_CORPO_ESTRANHO,
      MAL_LAVADO_TOTAL = :V_MAL_LAVADO,
      VASILHAMES_RETORNADOS_LAVAR = :O_TOTAL_LAVAR,
      CARREGADO_TOTAL = :O_TOTAL_CARGA_CALCULADA
  WHERE ID = :O_PRODUCAO_ID;

  SUSPEND;
END^

-- 5.3 PROCEDURE: ADICIONAR ITEM DE AVARIA / OCORRÊNCIA NA VISTORIA
CREATE OR ALTER PROCEDURE SP_ADICIONAR_AVARIA_ITEM (
    P_PRODUCAO_CONTROLE_ID BIGINT,
    P_FASE VARCHAR(20),            -- 'descarregamento' ou 'carregamento'
    P_TIPO_AVARIA VARCHAR(80),
    P_QUANTIDADE INTEGER,
    P_CATEGORIA VARCHAR(30),        -- 'avaria', 'compra', 'retorno_lavagem'
    P_DESCONTAR_MOTORISTA CHAR(1)
)
RETURNS (
    O_AVARIA_ID BIGINT
)
AS
  DECLARE VARIABLE V_CATEGORIA_AJUSTADA VARCHAR(30);
  DECLARE VARIABLE V_NOME_LOWER VARCHAR(80);
BEGIN
  V_NOME_LOWER = LOWER(TRIM(:P_TIPO_AVARIA));
  V_CATEGORIA_AJUSTADA = :P_CATEGORIA;

  -- Forçar categoria retorno_lavagem para corpo estranho ou mal lavado
  IF (V_NOME_LOWER = 'corpo estranho' OR V_NOME_LOWER = 'mal lavado') THEN
    V_CATEGORIA_AJUSTADA = 'retorno_lavagem';
  ELSE IF (V_NOME_LOWER CONTAINING 'compra' OR V_NOME_LOWER CONTAINING 'rota') THEN
    V_CATEGORIA_AJUSTADA = 'compra';

  INSERT INTO TB_AVARIAS_ITENS (
    UUID, PRODUCAO_CONTROLE_ID, FASE, TIPO_AVARIA, QUANTIDADE,
    CATEGORIA, DESCONTAR_MOTORISTA
  ) VALUES (
    'AV-' || NEXT VALUE FOR GEN_AVARIAS_ITENS,
    :P_PRODUCAO_CONTROLE_ID, :P_FASE, :P_TIPO_AVARIA, :P_QUANTIDADE,
    :V_CATEGORIA_AJUSTADA, :P_DESCONTAR_MOTORISTA
  ) RETURNING ID INTO :O_AVARIA_ID;

  SUSPEND;
END^

-- 5.4 PROCEDURE: CONCLUIR E REGISTRAR SAÍDA DA PORTARIA
CREATE OR ALTER PROCEDURE SP_REGISTRAR_SAIDA_PORTARIA (
    P_MOVIMENTO_ID BIGINT,
    P_OPERADOR_SAIDA VARCHAR(80)
)
RETURNS (
    O_STATUS VARCHAR(30),
    O_DATA_SAIDA TIMESTAMP
)
AS
BEGIN
  O_DATA_SAIDA = CURRENT_TIMESTAMP;
  O_STATUS = 'saida';

  UPDATE TB_MOVIMENTOS
  SET STATUS_MOVIMENTO = :O_STATUS,
      ETAPA_KANBAN = 'concluido',
      DATA_SAIDA = :O_DATA_SAIDA,
      OPERADOR_SAIDA = :P_OPERADOR_SAIDA
  WHERE ID = :P_MOVIMENTO_ID;

  -- Concluir produção se estiver em aberto
  UPDATE TB_PRODUCAO_CONTROLE
  SET PRODUCAO_CONCLUIDA = 'S',
      DATA_FIM = :O_DATA_SAIDA
  WHERE MOVIMENTO_ID = :P_MOVIMENTO_ID AND PRODUCAO_CONCLUIDA = 'N';

  SUSPEND;
END^

-- 5.5 PROCEDURE PARA RELATÓRIO E MINERAÇÃO DE DADOS (BI)
CREATE OR ALTER PROCEDURE SP_RELATORIO_PRODUCAO_PERIODO (
    P_DATA_INICIAL TIMESTAMP,
    P_DATA_FINAL TIMESTAMP,
    P_UNIDADE VARCHAR(20)
)
RETURNS (
    R_MOVIMENTO_ID BIGINT,
    R_CODIGO_PRODUCAO VARCHAR(30),
    R_PLACA VARCHAR(12),
    R_MOTORISTA VARCHAR(120),
    R_DATA_ENTRADA TIMESTAMP,
    R_DATA_SAIDA TIMESTAMP,
    R_DESCARREGADO INTEGER,
    R_CARREGADO INTEGER,
    R_RETORNO_LAVAR INTEGER,
    R_AVARIAS_REAIS INTEGER,
    R_TAMPAS INTEGER,
    R_STATUS VARCHAR(30)
)
AS
BEGIN
  FOR SELECT 
        M.ID, M.CODIGO_PRODUCAO, M.PLACA, M.MOTORISTA, M.DATA_ENTRADA, M.DATA_SAIDA,
        COALESCE(P.DESCARREGADO_TOTAL, 0),
        COALESCE(P.CARREGADO_TOTAL, 0),
        COALESCE(P.VASILHAMES_RETORNADOS_LAVAR, 0),
        COALESCE((
          SELECT SUM(A.QUANTIDADE) 
          FROM TB_AVARIAS_ITENS A 
          WHERE A.PRODUCAO_CONTROLE_ID = P.ID AND A.CATEGORIA = 'avaria'
        ), 0),
        COALESCE(P.TAMPAS_UTILIZADAS, 0),
        M.STATUS_MOVIMENTO
      FROM TB_MOVIMENTOS M
      LEFT JOIN TB_PRODUCAO_CONTROLE P ON P.MOVIMENTO_ID = M.ID
      WHERE M.DATA_ENTRADA BETWEEN :P_DATA_INICIAL AND :P_DATA_FINAL
        AND (:P_UNIDADE IS NULL OR :P_UNIDADE = '' OR M.UNIDADE = :P_UNIDADE)
      ORDER BY M.DATA_ENTRADA DESC
      INTO :R_MOVIMENTO_ID, :R_CODIGO_PRODUCAO, :R_PLACA, :R_MOTORISTA, :R_DATA_ENTRADA, :R_DATA_SAIDA,
           :R_DESCARREGADO, :R_CARREGADO, :R_RETORNO_LAVAR, :R_AVARIAS_REAIS, :R_TAMPAS, :R_STATUS
  DO
  BEGIN
    SUSPEND;
  END
END^

SET TERM ; ^

COMMIT;
